# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-24 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='picture',
            field=models.ImageField(upload_to='static/upload/goods'),
        ),
        migrations.AlterField(
            model_name='goodstype',
            name='gpicture',
            field=models.ImageField(upload_to='static/upload/goodstype'),
        ),
        migrations.AlterField(
            model_name='goodstype',
            name='tname',
            field=models.CharField(max_length=40),
        ),
    ]
