# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-24 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20180724_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodstype',
            name='tdesc',
            field=models.TextField(),
        ),
    ]
