# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-26 11:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20180724_1108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
