# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-26 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20180726_1953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AlterModelOptions(
            name='goodstype',
            options={'verbose_name': '商品类型', 'verbose_name_plural': '商品类型'},
        ),
        migrations.AlterField(
            model_name='goodstype',
            name='gpicture',
            field=models.ImageField(upload_to='static/upload/goodstype', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='goodstype',
            name='tdesc',
            field=models.TextField(verbose_name='商品描述'),
        ),
        migrations.AlterField(
            model_name='goodstype',
            name='tname',
            field=models.CharField(max_length=40, verbose_name='商品类型'),
        ),
        migrations.AlterModelTable(
            name='goods',
            table='goods',
        ),
        migrations.AlterModelTable(
            name='goodstype',
            table='goodType',
        ),
    ]
