# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-26 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20180726_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodstype',
            name='goods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.Goods'),
        ),
    ]
