# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-26 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_goodstype_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodstype',
            name='goods',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.Goods'),
        ),
    ]
