# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-26 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_auto_20180726_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goodtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.GoodsType'),
        ),
    ]
