# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-26 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_auto_20180726_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='hasbuy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.Goods', verbose_name='已买过'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goodtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.GoodsType', verbose_name='商品类型'),
        ),
    ]
