# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-26 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_auto_20180726_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='hasbuy',
        ),
        migrations.AddField(
            model_name='users',
            name='hasbuy',
            field=models.ManyToManyField(null=True, to='index.Goods', verbose_name='已买过'),
        ),
    ]
